# Generated by Django 4.1.2 on 2023-06-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firma', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('additional', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('auftragsnummer_ID', models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('auftraggeber', models.CharField(max_length=120)),
                ('auftragsdatum', models.DateField(null=True)),
                ('ausgeführt_bis', models.DateField(null=True)),
                ('auftragstext', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('angenommen', models.BooleanField(blank=True, default=False, null=True)),
                ('auftrag_abgeschlossen', models.BooleanField(blank=True, default=False, null=True)),
                ('auftragsfirma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Auftraege.adressen')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('tel', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField()),
                ('antwort', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rechnungsempfaenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firma', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('additional', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=7)),
                ('rechnungsdatum', models.DateField()),
                ('rechnungstext', models.TextField(blank=True)),
                ('rechnungspreis', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('auftragsnummer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auftraege.auftrag')),
                ('empfänger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auftraege.rechnungsempfaenger')),
            ],
        ),
        migrations.CreateModel(
            name='Auftragspositionen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('kostenstelle', models.CharField(blank=True, max_length=20, null=True)),
                ('referenz', models.TextField(blank=True, null=True)),
                ('einzelpreis', models.FloatField(blank=True, null=True)),
                ('mwst', models.IntegerField(blank=True, null=True)),
                ('anzahl', models.FloatField(blank=True, null=True)),
                ('empfänger', models.CharField(blank=True, max_length=120, null=True)),
                ('unterschrift', models.TextField(blank=True, null=True)),
                ('unterschrift_datum', models.DateField(blank=True, null=True)),
                ('position_abgeschlossen', models.BooleanField(blank=True, null=True)),
                ('fahrzeuge', models.CharField(blank=True, choices=[('BUS', 'Bus'), ('PKW', 'Pkw')], default='BUS', max_length=10, null=True)),
                ('pauschale', models.FloatField(blank=True, null=True)),
                ('wartezeit', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('auftragsnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auftraege.auftrag')),
                ('nach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nach', to='Auftraege.adressen')),
                ('von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='von', to='Auftraege.adressen')),
            ],
        ),
        migrations.AddField(
            model_name='auftrag',
            name='fahrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auftraege.fahrer'),
        ),
    ]
